# Generated by Django 4.2.7 on 2024-05-13 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractType', models.CharField()),
                ('SignatureDate', models.DateField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstateOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfficerName', models.CharField(max_length=50)),
                ('OfficerNumber', models.CharField(max_length=50)),
                ('OfficerMail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'AgentImma',
                'verbose_name_plural': 'AgentImmas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvaluateProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=200)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'EvaluateProperty',
                'verbose_name_plural': 'EvaluatePropertys',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PosterPicture', models.FileField(upload_to='')),
                ('PosterHeader', models.CharField()),
                ('PosterText', models.TextField()),
            ],
            options={
                'verbose_name': 'Poster',
                'verbose_name_plural': 'Posters',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyType', models.CharField(max_length=30)),
                ('PropertyImages', models.FileField(blank=True, null=True, upload_to='property_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('PropertyName', models.CharField(max_length=50)),
                ('PropertyLocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('SureName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('UserProfilePhoto', models.FileField(blank=True, null=True, upload_to='property_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('UserPwd', models.CharField(max_length=50)),
                ('UserMail', models.EmailField(max_length=254)),
                ('UserNumber', models.IntegerField()),
                ('UserRequiresUplaod', models.FileField(blank=True, null=True, upload_to='property_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'pdf', 'doc'])])),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainBackend.user')),
                ('UserStatus', models.BooleanField(choices=[(True, 'Owner'), (False, 'buyer')])),
            ],
            options={
                'verbose_name': 'buyer',
                'verbose_name_plural': 'buyers',
                'db_table': '',
                'managed': True,
            },
            bases=('mainBackend.user',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainBackend.user')),
                ('UserStatus', models.BooleanField(choices=[(True, 'Owner'), (False, 'buyer')])),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'db_table': '',
                'managed': True,
            },
            bases=('mainBackend.user',),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainBackend.operation')),
                ('RentPrice', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'db_table': '',
                'managed': True,
            },
            bases=('mainBackend.operation',),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainBackend.operation')),
                ('SellPrice', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sell',
                'verbose_name_plural': 'Sells',
                'db_table': '',
                'managed': True,
            },
            bases=('mainBackend.operation',),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costs', models.IntegerField()),
                ('PropertyId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainBackend.operation')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveBigIntegerField()),
                ('Status', models.BooleanField()),
                ('propertytId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainBackend.operation')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='PropertyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainBackend.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='OwnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainBackend.owner'),
        ),
    ]
