# Generated by Django 4.2.7 on 2024-07-17 16:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainBackend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserStatus', models.CharField(choices=[('Owner', 'Owner'), ('Buyer', 'Buyer'), ('Admin', 'Admin')], max_length=10)),
                ('SureName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('UserProfilePhoto', models.FileField(blank=True, null=True, upload_to='property_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('UserNumber', models.IntegerField(blank=True, null=True)),
                ('UserRequiresUplaod', models.FileField(blank=True, null=True, upload_to='property_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'pdf', 'doc'])])),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractType', models.CharField(max_length=100)),
                ('SignatureDate', models.DateField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstateOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfficerName', models.CharField(max_length=50)),
                ('OfficerNumber', models.CharField(max_length=50)),
                ('OfficerMail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'AgentImma',
                'verbose_name_plural': 'AgentImmas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvaluateProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=200)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'EvaluateProperty',
                'verbose_name_plural': 'EvaluatePropertys',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PosterPicture', models.FileField(upload_to='')),
                ('PosterHeader', models.CharField(max_length=50)),
                ('PosterText', models.TextField()),
            ],
            options={
                'verbose_name': 'Poster',
                'verbose_name_plural': 'Posters',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyType', models.CharField(choices=[(mainBackend.models.Sell, 'Sell'), (mainBackend.models.Rental, 'Rental')], max_length=30)),
                ('PropertyImages', models.FileField(blank=True, null=True, upload_to='property_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('PropertyOwningFiles', models.FileField(blank=True, null=True, upload_to='propertyOwning_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'pdf'])])),
                ('PropertyPrice', models.IntegerField()),
                ('PropertyName', models.CharField(max_length=50)),
                ('PropertyLocation', models.CharField(max_length=50)),
                ('verificationStatus', models.BooleanField(choices=[(True, 'verified'), (False, 'unverified')], default=False)),
                ('OwnerId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainBackend.operation')),
                ('RentPrice', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'db_table': '',
                'managed': True,
            },
            bases=('mainBackend.operation',),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainBackend.operation')),
                ('SellPrice', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sell',
                'verbose_name_plural': 'Sells',
                'db_table': '',
                'managed': True,
            },
            bases=('mainBackend.operation',),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costs', models.IntegerField()),
                ('PropertyId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainBackend.operation')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveBigIntegerField()),
                ('Status', models.BooleanField()),
                ('propertytId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainBackend.operation')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainBackend.property')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='PropertyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainBackend.property'),
        ),
    ]
